#!/bin/sh

set -eux

mkdir -p /system/basicimg /system/usr/local/bin
cp /usr/local/bin/basicimg-* /system/usr/local/bin/
echo "$1" > /system/basicimg/os
if [ "$#" -eq 2 ]; then
    echo "$2" > /system/basicimg/app
fi